#!/bin/bash

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";

f(){
  exec rlwrap sml "$SCRIPT_DIR"/src/top/sources.cm "$SCRIPT_DIR"/src/top/top.sml "$@"
  unset -f f;
}

f $@
